config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Customized Decidim core routes
  # Mount the Decidim routes manually to modify them more easily
  mount Decidim::Api::Engine => "/api"
  mount Decidim::Admin::Engine => "/admin"
  mount Decidim::System::Engine => "/system"

  # Root at the top so that the engines won't override this
  root to: "home#index"

  devise_for :users,
             class_name: "Decidim::User",
             module: :devise,
             router_name: :decidim,
             controllers: {
               invitations: "decidim/devise/invitations",
               sessions: "decidim/devise/sessions",
               confirmations: "confirmations",
               registrations: "registrations",
               passwords: "decidim/devise/passwords",
               omniauth_callbacks: "devise/omniauth_registrations"
             }

  devise_scope :user do
    post "omniauth_registrations" => "devise/omniauth_registrations#create"
  end

  authenticate(:user) do
    resource :account, only: [:show, :update, :destroy], controller: "account" do
      member do
        get :delete
      end
    end
  end

  scope module: 'decidim' do
    resource :locale, only: [:create]

    # CUSTOM START
    # Mount the needed component manifests to the root
    manifests = Decidim.component_manifests.select do |manifest|
      manifest.name == :proposals
    end
    manifests.each do |manifest|
      next unless manifest.engine

      constraints Decidim::ParticipatoryProcesses::CurrentComponent.new(manifest) do
        mount manifest.engine, at: "/", as: "decidim_participatory_process_#{manifest.name}"
      end
    end
    # CUSTOM END

    mount Decidim::Verifications::Engine, at: "/", as: "decidim_verifications"

    Decidim.global_engines.each do |name, engine_data|
      mount engine_data[:engine], at: engine_data[:at], as: name
    end

    authenticate(:user) do
      resources :conversations, only: [:new, :create, :index, :show, :update], controller: "messaging/conversations"
      resources :notifications, only: [:index, :destroy] do
        collection do
          delete :read_all
        end
      end
      resource :notifications_settings, only: [:show, :update], controller: "notifications_settings"
      resources :own_user_groups, only: [:index]

      get "/newsletters_opt_in/:token", to: "newsletters_opt_in#update", as: :newsletters_opt_in

      resource :data_portability, only: [:show], controller: "data_portability" do
        member do
          post :export
          get :download_file
        end
      end

      get "/authorization_modals/:authorization_action/f/:component_id(/:resource_name/:resource_id)", to: "authorization_modals#show", as: :authorization_modal

      resources :groups, except: [:destroy, :index, :show] do
        resources :join_requests, only: [:create, :update, :destroy], controller: "user_group_join_requests"
        resources :invites, only: [:index, :create, :update, :destroy], controller: "group_invites"
        resources :users, only: [:index, :destroy], controller: "group_members", as: "manage_users" do
          member do
            post :promote
          end
        end
        resources :admins, only: [:index], controller: "group_admins", as: "manage_admins" do
          member do
            post :demote
          end
        end

        member do
          delete :leave
        end
      end
    end

    resources :profiles, only: [:show], param: :nickname, constraints: { nickname: %r{[^\/]+} }, format: false
    scope "/profiles/:nickname", format: false, constraints: { nickname: %r{[^\/]+} } do
      get "following", to: "profiles#following", as: "profile_following"
      get "followers", to: "profiles#followers", as: "profile_followers"
      get "badges", to: "profiles#badges", as: "profile_badges"
      get "groups", to: "profiles#groups", as: "profile_groups"
      get "members", to: "profiles#members", as: "profile_members"
    end

    resources :pages, only: [:index, :show], format: false

    get "/search", to: "searches#index", as: :search

    get :organization_users, to: "users#index"

    get "/scopes/picker", to: "scopes#picker", as: :scopes_picker

    get "/static_map", to: "static_map#show", as: :static_map
    get "/cookies/accept", to: "cookie_policy#accept", as: :accept_cookies
    put "/pages/terms-and-conditions/accept", to: "tos#accept_tos", as: :accept_tos

    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all

    resource :follow, only: [:create, :destroy]
    resource :report, only: [:create]

    resources :newsletters, only: [:show] do
      get :unsubscribe, on: :collection
    end

    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end

    scope :oauth do
      get "/me" => "doorkeeper/credentials#me"
    end

    resources :participatory_process_steps, only: [:index], path: "steps", controller: 'participatory_processes/participatory_process_steps'
  end
end

app/controllers/concerns/decidim/participatory_space_context.rb
# frozen_string_literal: true

module Decidim
  # This module contains all the logic needed for a controller to render a participatory space
  # public layout.
  #
  module ParticipatorySpaceContext
    extend ActiveSupport::Concern

    class_methods do
      # Public: Called on a controller, it sets up all the surrounding methods to render a
      # participatory space's template. It expects the method `current_participatory_space` to be
      # defined, from which it will extract the participatory manifest.
      #
      # options - A hash used to modify the behavior of the layout. :only: - An array of actions on
      #           which the layout will be applied.
      #
      # Returns nothing.
      def participatory_space_layout(options = {})
        layout :layout, options
        before_action :authorize_participatory_space, options
      end
    end

    included do
      include Decidim::NeedsOrganization

      helper ParticipatorySpaceHelpers, IconHelper
      helper_method :current_participatory_space
      helper_method :current_participatory_space_manifest
      helper_method :current_participatory_space_context

      delegate :manifest, to: :current_participatory_space, prefix: true
    end

    private

    def current_participatory_space_context
      :public
    end

    def current_participatory_space
      raise NotImplementedError
    end

    def authorize_participatory_space
      space = current_participatory_space
      unless space
        return redirect_to "/404"
      end
      enforce_permission_to :read, :participatory_space, current_participatory_space: current_participatory_space
    end

    def layout
      current_participatory_space_manifest.context(current_participatory_space_context).layout
    end

    # Method for current user can visit the space (assembly or proces)
    def current_user_can_visit_space?
      (current_participatory_space.try(:private_space?) &&
       current_participatory_space.users.include?(current_user)) ||
        !current_participatory_space.try(:private_space?) ||
        (current_participatory_space.try(:private_space?) &&
        current_participatory_space.try(:is_transparent?))
    end

    def check_current_user_can_visit_space
      return if current_user_can_visit_space?
      flash[:alert] = I18n.t("participatory_space_private_users.not_allowed", scope: "decidim")
      redirect_to "/404"
    end
  end
end

app/controllers/decidim/participatory_processes/participatory_process_steps_controller.rb
# frozen_string_literal: true

module Decidim
  module ParticipatoryProcesses
    # A controller that holds the logic to show ParticipatoryProcessSteps in a
    # public layout.
    class ParticipatoryProcessStepsController < Decidim::ParticipatoryProcesses::ApplicationController
      include ParticipatorySpaceContext
      include Rails.application.routes.url_helpers # Fix the modified routes
      participatory_space_layout only: :index

      def index; end

      private

      def organization_participatory_processes
        @organization_participatory_processes ||= OrganizationParticipatoryProcesses.new(current_organization).query
      end

      def current_participatory_space
        request.env["decidim.current_participatory_space"]
      end
    end
  end
end

app/controllers/decidim_controller.rb
# Entry point for Decidim. It will use the `DecidimController` as
# entry point, but you can change what controller it inherits from
# so you can customize some methods.
class DecidimController < ApplicationController
end

app/helpers/decidim/cta_button_helper.rb
# frozen_string_literal: true

module Decidim
  # A Helper to render the Call To Action button.
  module CtaButtonHelper
    # Renders the Call To Action button. Link and text can be configured
    # per organization.
    def cta_button
      button_text = translated_attribute(current_organization.cta_button_text).presence || t("decidim.pages.home.hero.participate")

      link_to button_text, cta_button_path, class: "hero-cta button large button--sc"
    end

    # Finds the CTA button path to reuse it in other places.
    def cta_button_path
      if current_organization.cta_button_path.present?
        url = current_organization.cta_button_path
        url_opts = controller.default_url_options
        url += "?#{url_opts.to_query}" unless url_opts.empty?
        url
      elsif Decidim::ParticipatoryProcess.where(organization: current_organization).published.any?
        decidim_participatory_processes.participatory_processes_path
      elsif current_user
        decidim.account_path
      else
        decidim.new_user_registration_path
      end
    end
  end
end

app/helpers/decidim/map_helper.rb
# frozen_string_literal: true

module Decidim
  # This helper include some methods for rendering resources static and dynamic maps.
  module MapHelper
    # Renders a link to openstreetmaps with the resource latitude and longitude.
    # The link's content is a static map image.
    #
    # resource - A geolocalizable resource
    # options - An optional hash of options (default: { zoom: 17 })
    #           * zoom: A number to represent the zoom value of the map
    def static_map_link(resource, options = {})
      return unless resource.geocoded?

      zoom = options[:zoom] || 17
      latitude = resource.latitude
      longitude = resource.longitude

      map_url = "https://www.openstreetmap.org/?mlat=#{latitude}&mlon=#{longitude}#map=#{zoom}/#{latitude}/#{longitude}"

      link_to map_url, target: "_blank" do
        image_tag decidim.static_map_path(sgid: resource.to_sgid.to_s)
      end
    end

    def dynamic_map_for(markers_data)
      return if Decidim.geocoder.blank?

      map_html_options = {
        class: "google-map",
        id: "map",
        "data-markers-data" => markers_data.to_json,
        "data-here-app-id" => Decidim.geocoder[:here_app_id],
        "data-here-app-code" => Decidim.geocoder[:here_app_code]
      }
      content = capture { yield }.html_safe
      content_tag :div do
        content_tag(:div, "", map_html_options) + content
      end
    end
  end
end

app/helpers/decidim/menu_helper.rb
# frozen_string_literal: true

module Decidim
  # This module includes helpers to manage menus in layout
  module MenuHelper
    # Public: Returns the main menu presenter object
    def main_menu
      @main_menu ||= AppMenuPresenter.new(
        :menu,
        self,
        element_class: "menu-item menu-item-main-nav",
        active_class: "active"
      )
    end

    # Public: Returns the user menu presenter object
    def user_menu
      @user_menu ||= ::Decidim::InlineMenuPresenter.new(
        :user_menu,
        self,
        element_class: "tabs-title",
        active_class: "active"
      )
    end
  end
end

app/helpers/decidim/participatory_processes/participatory_process_helper.rb
# frozen_string_literal: true

module Decidim
  module ParticipatoryProcesses
    # Helpers related to the Participatory Process layout.
    module ParticipatoryProcessHelper
      # Public: Returns the dates for a step in a readable format like
      # "2016-01-01 - 2016-02-05".
      #
      # participatory_process_step - The step to format to
      #
      # Returns a String with the formatted dates.
      def step_dates(participatory_process_step)
        dates = [participatory_process_step.start_date, participatory_process_step.end_date]
        dates.map { |date| date ? localize(date.to_date, format: :default) : "?" }.join(" - ")
      end

      def category_link(category, options={})
        category_link = decidim_participatory_process_proposals.proposals_path(
          filter: {category_id: category.id}
        )
        link_to category_link, options do
          yield
        end
      end

      def category_ideas_count(category)
        if main_component
          Decidim::Proposals::Proposal.joins(:category)
            .except_rejected.except_withdrawn
            .where(
              decidim_component_id: main_component.id,
              decidim_categories: {id: category.id}
            ).count
        else
          0
        end
      end

      def total_ideas_count
        Decidim::Proposals::Proposal
          .except_rejected.except_withdrawn
          .where(decidim_component_id: main_component.id)
          .count
      end
    end
  end
end

app/helpers/decidim/proposals/application_helper.rb
# frozen_string_literal: true

module Decidim
  module Proposals
    # Custom helpers, scoped to the proposals engine.
    #
    module ApplicationHelper
      include Decidim::Comments::CommentsHelper
      include PaginateHelper
      include ProposalVotesHelper
      include ProposalEndorsementsHelper
      include Decidim::MapHelper
      include Decidim::Proposals::MapHelper
      include CollaborativeDraftHelper

      delegate :minimum_votes_per_user, to: :component_settings

      # Public: The state of a proposal in a way a human can understand.
      #
      # state - The String state of the proposal.
      #
      # Returns a String.
      def humanize_proposal_state(state)
        I18n.t(state, scope: "decidim.proposals.answers", default: :not_answered)
      end

      # Public: The css class applied based on the proposal state.
      #
      # state - The String state of the proposal.
      #
      # Returns a String.
      def proposal_state_css_class(state)
        case state
        when "accepted"
          "text-success"
        when "rejected"
          "text-alert"
        when "evaluating"
          "text-info"
        else
          "text-warning"
        end
      end

      # Public: The state of a proposal in a way a human can understand.
      #
      # state - The String state of the proposal.
      #
      # Returns a String.
      def humanize_collaborative_draft_state(state)
        I18n.t("decidim.proposals.collaborative_drafts.states.#{state}", default: :open)
      end

      # Public: The css class applied based on the collaborative draft state.
      #
      # state - The String state of the collaborative draft.
      #
      # Returns a String.
      def collaborative_draft_state_badge_css_class(state)
        case state
        when "open"
          "success"
        when "withdrawn"
          "alert"
        when "published"
          "secondary"
        end
      end

      def proposal_limit_enabled?
        proposal_limit.present?
      end

      def minimum_votes_per_user_enabled?
        minimum_votes_per_user.positive?
      end

      def proposal_limit
        return if component_settings.proposal_limit.zero?

        component_settings.proposal_limit
      end

      def votes_given
        @votes_given ||= ProposalVote.where(
          proposal: Proposal.where(component: current_component),
          author: current_user
        ).count
      end

      def current_user_proposals
        Proposal.where(component: current_component, author: current_user)
      end

      def follow_button_for(model)
        render partial: "decidim/shared/follow_button.html", locals: { followable: model }
      end

      def endorsers_for(proposal)
        proposal.endorsements.for_listing.map { |identity| present(identity.normalized_author) }
      end

      def form_has_address?
        @form.address.present? || @form.has_address
      end

      def authors_for(collaborative_draft)
        collaborative_draft.identities.map { |identity| present(identity) }
      end

      def show_voting_rules?
        return false unless votes_enabled?

        return true if vote_limit_enabled?
        return true if threshold_per_proposal_enabled?
        return true if proposal_limit_enabled?
        return true if can_accumulate_supports_beyond_threshold?
        return true if minimum_votes_per_user_enabled?
      end
    end
  end
end

app/helpers/decidim/proposals/proposals_helper.rb
# frozen_string_literal: true

module Decidim
  module Proposals
    # Custom helpers, scoped to the proposals engine.
    #
    module ProposalsHelper
      def current_category
        if filter.category_id.is_a?(String) && !filter.category_id.empty?
          Decidim::Category.find_by(id: filter.category_id)
        end
      end
    end
  end
end

app/views/decidim/shared/_announcement.html.erb
<%
options = local_assigns
options[:callout_class] ||= "info"
%>
<%= cell("decidim/announcement", local_assigns) %>

app/views/decidim/shared/_flag_modal.html.erb
<div class="reveal flag-modal" id="flagModal" data-reveal>
  <div class="reveal__header">
    <h3 class="reveal__title"><%= t(".title") %></h3>
    <button class="close-button" data-close aria-label="<%= t(".close") %>" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% if reportable.reported_by? current_user %>
    <p><%= t(".already_reported") %></p>
  <% else %>
    <% if false %>
      <p><%= t(".description") %></p>
    <% end %>

    <%= decidim_form_for form, url: url, method: :post do |f| %>
      <%= f.collection_radio_buttons :reason, [[:spam, t(".spam")], [:offensive, t(".offensive")], [:does_not_belong, t(".does_not_belong", organization_name: current_organization.name)]], :first, :last do |builder| %>
        <div class="radio">
          <%= builder.radio_button %>
          <%= builder.label { builder.text } %>
        </div>
      <% end %>
      <%= f.text_area :details, rows: 4 %>

      <div class="text-center">
        <%= f.submit t(".report") %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/decidim/shared/_login_modal.html.erb
<div class="reveal login-reveal" id="loginModal" data-reveal>
  <div class="reveal__header">
    <h3 class="reveal__title"><%= t(".please_sign_in") %></h3>
    <button class="close-button" data-close aria-label="Close modal"
      type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="row">
    <%= render "decidim/devise/shared/omniauth_buttons_mini" %>

    <div class="service-sign-in">
      <div class="columns">
        <div class="text-center">
          <p>
            <button class="h5" data-toggle="session session_closed session_open">
              <%= t("decidim.devise.sessions.new.sign_in_service_account") %>
              <span id="session_closed" data-toggler=".is-hidden">
                <i class="fa fa-chevron-down"></i>
              </span>
              <span id="session_open" class="is-hidden" data-toggler=".is-hidden">
                <i class="fa fa-chevron-up"></i>
              </span>
            </button>
          </p>
        </div>
      </div>

      <div class="columns medium-10 medium-centered">
        <div class="register-form-wrapper is-hidden" id="session" data-toggler=".is-hidden">
          <%= decidim_form_for(Decidim::User.new, as: :user, url: session_path(:user), html: { class: "register-form new_user" }) do |f| %>
            <div>
              <div class="field">
                <%= f.email_field :email, autofocus: true %>
              </div>
              <div class="field">
                <%= f.password_field :password, autocomplete: "off" %>
              </div>
            </div>
            <div class="actions text-center">
              <%= f.submit t("devise.sessions.new.sign_in"), class: "button hollow secondary large" %>
            </div>
          <% end %>
          <p class="text-center">
            <%= link_to t(".sign_up"), decidim.new_user_registration_path, class: "sign-up-link" %>
          </p>
          <p class="text-center">
            <%= link_to t("devise.shared.links.forgot_your_password"), new_password_path(:user) %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/decidim/shared/_results_per_page.html.erb
<div class="results-per-page">
  <div class="results-per-page__dropdown">
    <span class="results-per-page__text"><%= t(".label") %></span>
    <span class="results-per-page__options">
      <% Decidim::Paginable::OPTIONS.each do |per_page_option| %>
        <% if per_page.to_i == per_page_option %>
          <span class="current-per-page"><%= per_page_option %></span>
        <% else %>
          <%= link_to per_page_option, url_for(params.to_unsafe_h.merge(page: nil, per_page: per_page_option)), data: { per_page_option: per_page_option } %>
        <% end %>
        <% unless per_page_option == Decidim::Paginable::OPTIONS.last %>&nbsp;|&nbsp;<% end %>
      <% end %>
    </span>
  </div>
</div>

app/views/decidim/shared/_share_modal.html.erb
<div>
  <button id="share-button" class="button secondary expanded hollow" data-open="processShare">
    <i class="fa fa-share"></i>
    <%= t(".share") %>
  </button>
</div>
<div class="reveal" id="processShare" data-reveal>
  <div class="reveal__header">
    <h3 class="reveal__title"><%= t(".share") %>:</h3>
    <button class="close-button" data-close aria-label="<%= t(".close_window") %>" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="button-group text-center">
    <%= social_share_button_tag(decidim_page_title,
                                url: decidim_meta_url,
                                image: decidim_meta_image_url,
                                desc: h(decidim_meta_description),
                                via: decidim_meta_twitter_handler) %>
    <div class="social-share-button">
      <a class="button success ssb-icon" data-open="urlShare">
        <%= icon "link-intact" %>
      </a>
    </div>
  </div>
</div>
<div class="reveal" id="urlShare" data-reveal>
  <div class="reveal__header">
    <h3 class="reveal__title"><%= t(".share_link") %>:</h3>
    <button class="close-button" data-close aria-label="<%= t(".close_window") %>" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="input-group">
    <input class="input-group-field" type="text" value="<%= "#{decidim_meta_url}" %>" disabled="">
    <div class="input-group-button">
      <button class="button secondary hollow" data-copy-to-clipboard="<%= "#{decidim_meta_url}" %>"
        data-copy-to-clipboard-success="<%= t(".copied") %>">
        <%= icon 'clipboard' %>
        <%= t(".copy") %>
      </button>
    </div>
  </div>
</div>